### ISSUE TITLE
Can't get the response of a POST

### ISSUE THREAD

**Issue by roupify** [marcodave/protractor-http-client#1] opened 2018-03-16 20:11 UTC
I'm trying to use make a POST, but the statusCode of the response is always an object. I use the same test that you made in your lib, and I can't make it work. This is my test :
```
const http: HttpClient = new HttpClient('https://httpbin.org');

  let response: ResponseWrapper = http.post('/post', 'param1=value1&param2=value2', {
    'Content-Type': 'application/x-www-form-urlencoded'
  });
  expect(response.statusCode).to.equal(200);
  expect(response.header('Content-Type')).to.equal('application/json');
  expect(response.jsonBody.get('form').get('param1')).to.equal('value1');
  expect(response.jsonBody.get('form').get('param2')).to.equal('value2');

  response = http.post('/post', {
    my: { nice: ['json', 'object'] }
  });
  expect(response.statusCode).to.equal(200);
  expect(response.header('Content-Type')).to.equal('application/json');
  expect(
    response.jsonBody
      .get('json')
      .get('my')
      .get('nice')
      .get(0)
  ).to.equal('json');
```

This is the error in my console : ```AssertionError: expected { Object (flow_, stack_, ...) } to equal 200```

My setup : Protractor, Chai, Protractor-cucumber-framework

**Comment by marcodave** [comment] 2018-03-17 10:39
Hi ,can you please share your `package.json`, and the protactor config?
it looks like, that the chai library is not waiting for the Promise returned by the `response.statusCode`

According to the [protractor documentation](https://github.com/angular/protractor/blob/master/docs/frameworks.md), you have to use chai-as-promised, and use it like this
```
var chai = require('chai');
var chaiAsPromised = require('chai-as-promised');

chai.use(chaiAsPromised);
var expect = chai.expect;
```

**Comment by roupify** [comment] 2018-03-17 13:34
Here it is!

```js
//test.steps.ts
Then(/^status code need to be 200$/, next => {
  const http: HttpClient = new HttpClient('https://httpbin.org');

  const response = http.post('/post', 'param1=value1&param2=value2', {
    'Content-Type': 'application/x-www-form-urlencoded'
  });
  expect(response.statusCode).to.eventually.equal(200).and.notify(next);
});
```

```
// error in console
Error: function timed out after 5000 milliseconds
```

```js
// protractor.conf.js
exports.config = {
  allScriptsTimeout: 11000,
  capabilities: {
    browserName: 'chrome'
  },
  directConnect: true,
  baseUrl: 'http://localhost:4200/',

  // Specs here are the cucumber feature files
  specs: ['./e2e/features/*.feature'],
  ignoreUncaughtExceptions: true,

  // Use a custom framework adapter and set its relative path
  framework: 'custom',
  frameworkPath: require.resolve('protractor-cucumber-framework'),

  // cucumber command line options
  cucumberOpts: {
    // require step definition files before executing features
    require: ['./e2e/config-chai.ts', './e2e/steps/**/*.ts'],
    
    ...
  },

  // Enable TypeScript for the tests
  onPrepare() {
    require('ts-node').register({
      project: 'e2e/tsconfig.e2e.json'
    });
  }
};
```

```js
//config.chai.js
import * as chai from 'chai';
import * as chaiAsPromised from 'chai-as-promised';

chai.use(chaiAsPromised);
```

```json
// package.json
{
  "name": "test",
  "version": "0.0.1",
  "license": "MIT",
  "scripts": {
    "api-mock": "cd api-mock && npm start",
    "start": "start ng serve -o && start nodemon ./api-mock/api-mock.js",
    "e2e": "concurrently --kill-others --success first \"npm run api-mock\" \"ng e2e --port 4200 --no-webdriver-update\""
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^5.2.0",
    "@angular/common": "^5.2.0",
    "@angular/compiler": "^5.2.0",
    "@angular/core": "^5.2.0",
    "@angular/forms": "^5.2.0",
    "@angular/http": "^5.2.0",
    "@angular/platform-browser": "^5.2.0",
    "@angular/platform-browser-dynamic": "^5.2.0",
    "@angular/router": "^5.2.0",
    "@ngx-translate/core": "^9.1.1",
    "@ngx-translate/http-loader": "^2.0.1",
    "core-js": "^2.4.1",
    "intl": "^1.2.5",
    "moment": "^2.21.0",
    "rxjs": "^5.5.6",
    "zone.js": "^0.8.19"
  },
  "devDependencies": {
    "@angular/cli": "~1.7.3",
    "@angular/compiler-cli": "^5.2.0",
    "@angular/language-service": "^5.2.0",
    "@types/cucumber": "^4.0.1",
    "@types/jasmine": "~2.8.3",
    "@types/jasminewd2": "~2.0.2",
    "@types/node": "~6.0.60",
    "axe-webdriverjs": "^1.3.0",
    "chai": "^4.1.2",
    "chai-as-promised": "^7.1.1",
    "codelyzer": "^4.0.1",
    "concurrently": "^3.5.1",
    "cucumber": "^4.0.0",
    "http-server": "^0.11.1",
    "jasmine-core": "~2.8.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~2.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "ng2-mock-component": "^0.1.1",
    "nodemon": "^1.17.2",
    "npm-watch": "^0.3.0",
    "protractor": "~5.1.2",
    "protractor-cucumber-framework": "^4.2.0",
    "protractor-http-client": "^1.0.4",
    "protractor-multiple-cucumber-html-reporter-plugin": "^1.5.0",
    "ts-node": "~4.1.0",
    "tslint": "~5.9.1",
    "typescript": "~2.5.3"
  }
}
```

**Comment by marcodave** [comment] 2018-03-17 14:17
Thanks for sharing. Couple of  questions: 
1. have you tried your setup with a regular browser + protractor interaction? i.e. something like
`expect(element(by.id("some-id")).getText()).to.eventually.equal("Some text")`

2. in the original message, you did not use `.to.eventually.equal(200)`, try adding the eventually part and see if it gets the same error

**Comment by roupify** [comment] 2018-03-19 12:47
the chai-as-expected work well because I can get any other promises : ```expect(browser.getTitle()).to.eventually.equal('title');```

**Comment by marcodave** [comment] 2018-03-19 19:06
I re-created locally your setup, also adding the .feature file necessary for cucumber, as the following
```
Feature: test

Scenario:
    Then status code need to be 200
```
the `test.steps.ts` file needed tweaking, like adding 
```
import {Then} from "cucumber";
import {HttpClient} from "protractor-http-client";
import * as chai from "chai";
const expect = chai.expect;
```
I cannot reproduce the problem. Running plain protractor with `node_modules/.bin/protractor` it gives me
```
.

1 scenario (1 passed)
1 step (1 passed)
```

**Comment by roupify** [comment] 2018-03-20 20:08
I have maybe an idea why it doesn't work on my computer. It's maybe because i'm behind a corporate proxy...

**Comment by marcodave** [comment] 2018-03-22 19:54
@rousseaufiliong I'm closing this issue since I cannot replicate it.

**Closed as completed by marcodave** 2018-03-22 19:54 UTC
